### ISSUE TITLE
Onclick option list not working

### ISSUE THREAD

**Issue by ChocoMomo** [yury-dymov/react-autocomplete-input#1]
When clicking on the list the value isn't set at all.

**Comment by yury-dymov** [comment]
Hi @ChocoMomo, 

may I ask you to provide an example of the code?

I just checked my demo https://yury-dymov.github.io/react-autocomplete-input/, clicked an option in the list and it worked.

**Comment by Zuyderwijk** [comment]
@yury-dymov @ChocoMomo which browser? i'm guessing it has to do with the fact it's not setting a value because it can't register the click/tap event.

**Comment by yury-dymov** [comment]
@ChocoMomo @Zuyderwijk good note. Anyway, please help me reproduce the issue, so I could resolve it. I am using this package in production for quiet some time so I am also interested in fixing it in case smthing is broken

**Comment by yury-dymov** [comment]
@ChocoMomo, closed. Feel free to reopen after you'll be able to provide more information

**Comment by yury-dymov** [comment]
fixed here: https://github.com/yury-dymov/react-autocomplete-input/issues/7
