### ISSUE TITLE
Build tsc && vite

### ISSUE THREAD

**Issue by Mimouss56** [yury-dymov/react-autocomplete-input#100]
Error with TS

`react-autocomplete-input/dist/bundle.js' implicitly has an 'any' type.`

`Try `npm i --save-dev @types/react-autocomplete-input` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-autocomplete-input';``
Not Work

**Comment by yury-dymov** [comment]
Closed via https://github.com/yury-dymov/react-autocomplete-input/pull/103
