### ISSUE TITLE
Error in TypeScript definitions

### ISSUE THREAD

**Issue by szaleq** [yury-dymov/react-autocomplete-input#106]
There is an error in type definition file in line `26`. `IntrinsicAttributes` is not resolved correctly, so it gets cast to `any` and therefore entire `AutocompleteTextFieldProps` result being `any` type. It should be `JSX.IntrinsicAttributes` instead.

**Comment by dzsodzso63** [comment]
My workaround
```typescript
// Add to one of your local d.ts files

type IntrinsicAttributes = JSX.IntrinsicAttributes;
```

**Comment by freshgiammi** [comment]
Hi @yury-dymov this isn't fixed, as the correct type has been added but not imported. I have created a [PR](https://github.com/yury-dymov/react-autocomplete-input/pull/132) to solve this 👍
