### ISSUE TITLE
AutoComplete does not work when add new item with uppercase chars

### ISSUE THREAD

**Issue by kafeltz** [yury-dymov/react-autocomplete-input#12]
Access the demo page: https://yury-dymov.github.io/react-autocomplete-input/

Add a new option with capital letters, example BANANA.

Go up the type `@B` and it will *not* show the `BANANA` in the list.

Looks like some matching issue in the core.

**Comment by yury-dymov** [comment]
Thank you for the feedback, will have a look tonight

**Comment by kafeltz** [comment]
Fix for this in this PR https://github.com/yury-dymov/react-autocomplete-input/pull/16

It is the second commit I did, since you did not yet accept my last PR.

**Comment by yury-dymov** [comment]
Ok, I would prefer to control case-sensitive part with an optional prop (by default case-insensitive), I will also expose an optional prop, so people could override comparison logic by providing a function. 

As for the bug with "enter" on unselected, proposed solution seems to be perfect. I will try to play with corner cases to make sure that it works 100% of times

**Comment by yury-dymov** [comment]
Once again, above is nonsense. Thank you for a very good catch and a proper fix. Updated package published

**Comment by kafeltz** [comment]
I agree the props for case-sensitive is a good ideia.
