### ISSUE TITLE
Example in README for onChange when passing a value prop

### ISSUE THREAD

**Issue by fntn** [yury-dymov/react-autocomplete-input#128]
In the README under [`value`](https://github.com/yury-dymov/react-autocomplete-input?tab=readme-ov-file#value--string) it says:

> Widget supports both controlling options: by value and by state. If you explicitly pass `value` prop, you have to update it manually every time `onChange` event is emitted. If you don't pass `value` prop, then widget uses internal state for value manipulation.

Is it possible to provide an example of how to retrieve the updated value so that it can be managed and updated in custom state by the `onChange` callback?

**Comment by fntn** [comment]
This seems to work:

```
onChange={(val) => { console.log({ val }); }}
```

Would still welcome any alternatives or improvements.

**Comment by yury-dymov** [comment]
That is correct ^
