### ISSUE TITLE
ERROR in ./src/index.jsx in demo

### ISSUE THREAD

**Issue by kafeltz** [yury-dymov/react-autocomplete-input#13]
This error is shown when doing in ./demo/ folder `npm run build`:

![image](https://user-images.githubusercontent.com/1765469/35747269-cd2d7608-0830-11e8-942b-a8949993f85d.png)

This is caused by wrong path in the import.

Im sending a PR to fix this.

**Comment by kafeltz** [comment]
https://github.com/yury-dymov/react-autocomplete-input/pull/14

**Comment by yury-dymov** [comment]
It was undocumented but to make things work, you had to build the lib first and then build the demo. 

You PR made things simpler and more intuitive, so I want to say a warm thank you for that :)
