### ISSUE TITLE
Trigger completion then add further hint

### ISSUE THREAD

**Issue by vanjaoljaca** [yury-dymov/react-autocomplete-input#130]
Hi, thanks for the control. I'm trying to type something like '#wor<enter>' and have it autocomplete to '#working', but currently it autocompletes to '#wor#working'

Am I misconfiguring the control or is it something unsupported?

My completion setup looks a bit like this: 
<img width="411" alt="image" src="https://github.com/yury-dymov/react-autocomplete-input/assets/31779/567198e3-f0ca-4903-bb07-70b134a2afe4">

Video example
https://github.com/yury-dymov/react-autocomplete-input/assets/31779/64a82530-42f1-4d75-9eae-9fae1e01ead6

Repro

import TextInput from 'react-autocomplete-input';
import 'react-autocomplete-input/dist/bundle.css';

<TextInput trigger={["#", "#w"]} options={{"#": ["work", "workblog"], "#w": ["work", "workblog"]}} />

If I slice off the start of the completion text it works as expected, but looks a bit awkward in the drop down box

<img width="388" alt="image" src="https://github.com/yury-dymov/react-autocomplete-input/assets/31779/13e3f627-c08f-4c24-8a3a-b1c0d43e9de7">
<img width="342" alt="image" src="https://github.com/yury-dymov/react-autocomplete-input/assets/31779/3dbfa314-912d-4ba5-a2c8-ea6c7528efb5">

Any known workaround or suggestion?

**Comment by yury-dymov** [comment]
Yeah, your setup looks a bit confusing to me. Something like
```
<TextInput trigger="#" options={ ["work", "workblog"]} />
```
Should probably work unless I am misunderstanding your use-case...

**Comment by vanjaoljaca** [comment]
hm seems you are right, i'm not sure what I did wrong first time to think that won't work for me. for some reason I did that long winded way and it was unnecessary. thanks for reply
