### ISSUE TITLE
Feature Request: position

### ISSUE THREAD

**Issue by kafeltz** [yury-dymov/react-autocomplete-input#17]
I wonder if it be easy to add a position like north, south, east and west for the popup when pressing `@`.

Currently the component has offsetX and offsetY, but this is not enough. I'm in a need to show the popup above the input field because I have no space to show at the bottom.

I could do a PR but would be nice to discuss this a little bit before coding.

**Comment by yury-dymov** [comment]
Sounds more like a very specific use-case, rather than something that might be valuable for many. 
Feel free to file the PR, maybe your code will help to change my opinion.

**Comment by kafeltz** [comment]
I toke a look in the code and I changed the CSS and it's very easy to do it. Just change the CSS attribute `top` to `bottom`.

Take a look in the line [363](https://github.com/yury-dymov/react-autocomplete-input/blob/master/src/AutoCompleteTextField.jsx#L363).

Still, I think the list shown in the popup should be inverse ordered because the first match it will be in the top instead close to the textarea.

The result it will be:
![image](https://user-images.githubusercontent.com/1765469/36748698-65a1c024-1bd7-11e8-8045-eef8c6aef50c.png)

And without, as it is right now it is like this:
![image](https://user-images.githubusercontent.com/1765469/36748771-958154da-1bd7-11e8-8947-4655efbbd41d.png)

**Comment by yury-dymov** [comment]
Looks convincing :) 

Well, I want to keep the default behavior as it is but now I don't mind to have an option to control the options block position. Feel free to file a PR.
