### ISSUE TITLE
Update Component prop-type to expect a function

### ISSUE THREAD

**Issue by ellerynz** [yury-dymov/react-autocomplete-input#19]
Hey there,

Thanks for putting this together. 

I'm passing in a textarea with extra bells and whistles and I'm using this plugin to add the autocomplete behaviour to that textarea. That is all working fantastically well! E.g.

```jsx
<TextInput Component={MySpecialTexarea} ...
```

The only annoyance is the prop-type check is expecting a string so there are warnings in the console. Expecting a string makes sense for 'input' or 'textarea' but I'm passing in a function. Maybe that's not an expected use-case?

Would you be open to updating the prop-types to something like:

```js
Component: PropTypes.oneOfType([
  PropTypes.string,
  PropTypes.func,
]),
```

**Comment by yury-dymov** [comment]
Sure, feel free to file a PR

**Comment by ellerynz** [comment]
Sweet as—I'll cut a PR later on

**Comment by yury-dymov** [comment]
Thanks!
