### ISSUE TITLE
Using bounding client rect means the input cannot be inside a position-relative parent

### ISSUE THREAD

**Issue by rhagigi** [yury-dymov/react-autocomplete-input#2]
https://github.com/yury-dymov/react-autocomplete-input/blob/master/src/AutoCompleteTextField.jsx#L276 

This library is using left: boundingClientRect(el).left, which is the offset from the viewport. It should use el.offsetLeft, as what it's positioning is an absolutely positioned element, which means it needs to know the textarea's starting left *within the closest relative position parent* (or the viewport).

**Comment by yury-dymov** [comment]
Hmm, thank you for the feedback, will test soon and update if it will work as expected.
You can also do PR if you would like to :)

**Comment by yury-dymov** [comment]
@rhagigi, thank you for the feedback once again.

Closed via https://github.com/yury-dymov/react-autocomplete-input/commit/4e11d679bdb810a41f724cf91279fa4ea240f278

Let me know if I can further improve the package.
