### ISSUE TITLE
Spaces In Input do not count as changes to text

### ISSUE THREAD

**Issue by FatherNelson** [yury-dymov/react-autocomplete-input#24]
I am working on an application where I need to be able to take inputs of the form "foo bar"  as well as "foo".  I am storing the results of the autocompletion upon pressing enter, and have encountered two problems. 1, when I press enter to use an autocomplete option, this value is not passed to the handleRequestOptions function like is shown in the example code. In fact, my key handler that detects when enter is struck to submit the returned "part", does not even fire when I press enter to fill an autocomplete. 2, the lack of an ability to set an escape character prevents users of the package to allow users to pass in entries that have spaces. I guess my question is, is there a way to modify the package in order to allow for the user to set an escape character? Even better, is there a way to pull the whole value field from a text area using autocomplete? 

-FatherNelson

**Comment by yury-dymov** [comment]
Hi @FatherNelson, 

I don't mind to help, but I would kindly ask for a code snippet, which I can just grab and easily reproduce the issue. Otherwise, it would take me more time to resolve the issue, then I am feeling OK to invest

**Comment by yury-dymov** [comment]
Closed due to inactivity. Feel free to re-open once requested stuff is provided
