### ISSUE TITLE
Customize spacer

### ISSUE THREAD

**Issue by Flamefork** [yury-dymov/react-autocomplete-input#28]
**Context**
I'm implementing a form which has inputs of two kinds:
1. comma separated tokens (e.g. `'asd, qwe, zxc'`). In this case, it would be great to insert `', '` after token on completion instead of `' '`.
2. filters (e.g. `'asd=1;qwe=2'`), with spaces forbidden in the expression (e.g. `'asd = 1'` is incorrect). In this case it would be great to insert no space after token on completion.

**Problem**
Currently, the space character that is inserted after the completion is hardcoded.

**Proposal**
Introduce `spacer: PropTypes.string` with default value `' '` to insert after the token on completion.

**Comment by Flamefork** [comment]
I'd implement this change if it sounds reasonable.
Any thoughts/advice?

**Comment by yury-dymov** [comment]
Sure, go ahead, I like your suggestion
