### ISSUE TITLE
Multiply trigger! 

### ISSUE THREAD

**Issue by Kronenberg** [yury-dymov/react-autocomplete-input#4]
Hey! Question is: i want to trigger this dropdown on ':' and '!' in different cases! Is it real to do this?

**Comment by yury-dymov** [comment]
Hey @Kronenberg,

This case is not supported. Feel free to fork and implement this feature. It should be straightforward.

Kind regards,
Yury

**Comment by Kronenberg** [comment]
Thx a lot @yury-dymov! Have a nice day!
