### ISSUE TITLE
Invalid prop 'Component' supplied when using a custom component

### ISSUE THREAD

**Issue by jsheffers** [yury-dymov/react-autocomplete-input#40]
I'm trying to implement this with the TextareaAutosize component from Material UI.  I'm creating a functional component and including it.  It works, however, it throws a warning in the console:

```Warning: Failed prop type: Invalid prop `Component` supplied to `t`.```

It seems to function properly.  Should I be doing this a different way?  Codesandbox with this replicated:

```javascript
const CustomTextarea = forwardRef((props, ref) => (
  // If I don't forward the ref I get an error...
  <TextareaAutosize
    placeholder="Material-ui through custom component..."
    {...props}
    ref={ref}
  />
));

<TextInput
    Component={CustomTextarea}
    options={["One", "Two", "Three", "Four", "Five"]}
    onChange={handleChange}
    value={typingMessage}
/>
```

Full example: https://codesandbox.io/s/fervent-hamilton-8pt2z

**Comment by yury-dymov** [comment]
```
Component: PropTypes.oneOfType([
    PropTypes.string,
    PropTypes.func,
  ]),
```
This is current validation. Maybe something is missing but I don't have time to support this at the moment, so I will gladly review and merge PR. 

Given that it is a warning, I would just ignore it for now. I don't plan do any significant changes here, so you should be good

**Comment by silverwind** [comment]
I guess [PropTypes.elementType](https://github.com/facebook/prop-types/pull/211) might solve it.
