### ISSUE TITLE
Autocomplete does not work at the beginning of an input.

### ISSUE THREAD

**Issue by oolleegg55** [yury-dymov/react-autocomplete-input#5]
In the docs we have the notice:

> Keep in mind that user have to input at least one extra character to make option list available if empty trigger is used.

It is a very inconvenient restriction. How can it be avoided?

**Comment by yury-dymov** [comment]
Please describe the flow.

Do you want to show all autocomplete options all the time? Doesn't seem like textarea use-case. Or did I miss something?

**Comment by oolleegg55** [comment]
I tried it with an input element and set _trigger_ as empty string.
I want to use it as autocomplete for each word in an input but now first word isn't served.

Maybe this gif would show:
https://myefe.com/wp-content/uploads/sites/2/2017/03/Peek-2017-03-24-09-01.gif

**Comment by yury-dymov** [comment]
ok, I see. Will have a look in the weekend. PRs are also welcome :)

**Comment by oolleegg55** [comment]
Oh, the getMatch function is a little tricky. I'm not sure I could change it properly. :smile:
