### ISSUE TITLE
Input characters were not correct with IME Keyboard

### ISSUE THREAD

**Issue by ngocbnu213** [yury-dymov/react-autocomplete-input#66]
I faced a big trouble with Japanese keyboard. When I typed a single character, it seem to be double.
I think it related to IME string.

https://github.com/facebook/react/issues/3926

On your demo [https://yury-dymov.github.io/react-autocomplete-input/](url) I did not face to this problem.

My code did not have any thing specific
`<TextInput
                  Component="input"
                  options={domains}
                  value={mailAddress}
                  onChange={handleChangeEmail}
                />`

`mailAddress` is a props comes from `mapStateToProp`
`handleChangeEmail` will dispatch an action to reducer then update component again.

Do you have any idea about this case? How can I solve this problem?

https://user-images.githubusercontent.com/64132647/132298919-52826492-0ccd-432b-95ed-77309615b7b8.MOV

**Comment by ngocbnu213** [comment]
I also faced to new problem. Let me explain.
As you can see, when I type some thing, helper list will be available. Then I select one of option, after I close alert and tap to somewhere, my IME string will be appear. Expected in this case that IME string should be displayed 2 times.

https://user-images.githubusercontent.com/64132647/133008634-916b0a60-48b5-40b4-9542-d23fe1f25679.mp4

**Comment by yury-dymov** [comment]
This might have something to do with `regex` prop. Likely overriding it with one, which supports Japanese encondings properly might help
