### ISSUE TITLE
CSS clasess of Bundle.css wont work

### ISSUE THREAD

**Issue by Laloses** [yury-dymov/react-autocomplete-input#69]
I dont know if is a problem with the react-bootstrap form but the ul element is not adding the class react-autocomplete-input of the Bundle.css it just apears like a normal ul and moves everything inside the form-group.

I have my code like this:

```
<form id="submitSearchProdMov" onSubmit={this.submitSearchProdMov}>
      <div className="input-group mb-3">
              <span className="input-group-text " id="productoBuscar">Producto</span>
              <Col>
                  <TextInput trigger="" Component="input" id="searchProductosMovimiento" className="form-control"  placeholder="ej. Miel-liquida" options={this.state.listaSugerencias}/>
              </Col>
              <input id="cantidadProductoMovimiento" type="number" className="form-control" placeholder="Cantidad" min="1" aria-label="Cantidad" aria-describedby="cantidadProducto" required/>
              <button className="btn btn-outline-success" type="submit">Agregar</button>
      </div>
</form>
```

And the result is just awful
![image](https://user-images.githubusercontent.com/46451243/136994426-68e8bb44-6774-4d0a-ab93-0f3109d41d00.png)

**Comment by yury-dymov** [comment]
I think react-bootstrap did some breaking changes and since I no longer using this, I didn't have time to catch up

**Comment by yury-dymov** [comment]
Closing due inactivity
