### ISSUE TITLE
cannot select value from list with click

### ISSUE THREAD

**Issue by malindamiller** [yury-dymov/react-autocomplete-input#7]
Hi when I select on option from the autocomplete list with the 'enter' key it works, when i try to select with a mouse click, it just makes the list go away and the text box shows  only the part I typed in.  I am on Chrome.

**Comment by yury-dymov** [comment]
Hi @malindamiller, thank you for your feedback. I tried to reproduce the issue but everything works fine for me (https://yury-dymov.github.io/react-autocomplete-input/). Maybe you could give me a better idea, how this can be reproduced or some code snippets?

**Comment by malindamiller** [comment]
I am not sure how to reproduce it. I am calling the <TextInput> in a return method that is called from the render function. 
example:
<div>{this.modalWindow(item)}</div>
and then I am returning the <TextInput> inside the modalWindow(item) function\. But other than that I am calling it in it's most basic form(just as you did in the example). It's just strange to me that it can be selected with enter, but not click.

**Comment by yury-dymov** [comment]
Oh, now I see. I guess this should be somehow related to a z-index thing. 

For some reason browser not propagating your click. Not sure that it is you or me. If you could make a simple app for me, where an issue is easily reproducible, I will be able to fix it within a week (but probably day or two).

**Comment by malindamiller** [comment]
Thank you! I have recreated the problem, simply by running create-react-app
and then adding the autocomple input.

https://github.com/malindamiller/autoComplete-demo

**Comment by yury-dymov** [comment]
Awesome! I will try to come with a fix by Tuesday or earlier

**Comment by yury-dymov** [comment]
Still works fine for me :/
https://www.dropbox.com/s/n6n663mdtpct6tq/not_repro.mov?dl=0

**Comment by malindamiller** [comment]
@yury-dymov Thanks for your help.

macOS Sierra 10.12.3
Chrome Version 60.0.3112.101 (Official Build) (64-bit)

**Comment by austinkelleher** [comment]
@yury-dymov First off, great library! Very helpful.

I am also seeing this issue.

![aug-20-2017 18-54-08](https://user-images.githubusercontent.com/3771924/29499191-7c75e774-85d9-11e7-9a29-523a5b97f8f9.gif)

macOS Sierra 10.12.5
Chrome Version 60.0.3112.101 (Official Build) (64-bit)

I also did a little digging. I added a debug statement inside of the `onClick` here: https://github.com/yury-dymov/react-autocomplete-input/blob/master/src/AutoCompleteTextField.jsx#L315 and it seems to never be getting into `onClick`.

Thoughts? Thanks in advance.

**Comment by yury-dymov** [comment]
@austinkelleher I am on 10.12.5, Chrome has the same version and everything works fine for me :/ Will try to reproduce and hopefully fix tomorrow with clean cache / fresh install.

**Comment by yury-dymov** [comment]
@austinkelleher @malindamiller I just can't reproduce it :/

One thought popped into my mind: please try to reproduce the issue in incognito mode. If an issue is not reproducible this way, we may suspect a Chrome extension...

**Comment by yury-dymov** [comment]
Fixed (may test here https://yury-dymov.github.io/react-autocomplete-input/ but don't forget to clean cache). Feel free to re-open if you still able to reproduce

**Comment by austinkelleher** [comment]
@yury-dymov thank you so much for your quick fix! It works great!

**Comment by malindamiller** [comment]
Thank you for taking the time to fix this! 
Malinda
