### ISSUE TITLE
Can I add images with string in options?

### ISSUE THREAD

**Issue by upworker00852** [yury-dymov/react-autocomplete-input#70]
I have found your code and tested. That 's good. But I have one problem.

I am going to display username and user avatar in autocomplete when input "@", but I knew that can't add images in this autocomplete.
Would you please help me to solve this problem?
Thank you.

**Comment by yury-dymov** [comment]
I know it's almost a year late but if you or someone will fire a PR with a custom option rendered prop, I would be happy to merge

**Comment by yury-dymov** [comment]
duplicate of #45
