### ISSUE TITLE
Auto Scroll not working inside the dropdown on keyboard navigation

### ISSUE THREAD

**Issue by nithin397** [yury-dymov/react-autocomplete-input#73]
Let there be 10-15 records available in options and set maxOptions  to 5. Now use keyboard for navigation. When cursor down is pressed at the 5th record, the selection changes to 6th record (but only the top 5 are shown in the options). Auto scroll to the selected options does not happen and selected option is not visible for exact selection.
By the way, Thank you for this control. Hope this issue will get rectified.

**Comment by yury-dymov** [comment]
Hi, thank you for the kind words. I don't have capacity to support that but I am still merging good PRs
