### ISSUE TITLE
Dev Dependencies

### ISSUE THREAD

**Issue by njt1982** [yury-dymov/react-autocomplete-input#8]
Hi,

Trying to use this on a React Native and I get errors about the es2015 and stage-0 presets being unavailable. I had to do this:

```
yarn add --dev babel-preset-es2015
yarn add --dev babel-preset-stage-0
```

And then restart the simulator and packager.

Now maybe I should have had those anyway ;) but if they are dependencies for running I suggest that either:

a) They are added so yarn will install them as dependencies
or
b) There is an FAQ/Notes section on the project to suggest installing them?

What do you think?

**Comment by yury-dymov** [comment]
Hey @njt1982, thank you for your feedback!

If you are using npm package, then you are linking with compiled version and you don't need babel-presets. They are used for the compilation only and not for running.

If you are hacking stuff and modifying my package, then all dev deps should be installed. This is default approach for any package, not just mine.

Maybe I misunderstood your issue though.

**Comment by njt1982** [comment]
Hi,

So it is using the compiled (dist) version as when I look at the file in node_modules, it is incomprehensible to the human eye ;) 

However, it's being included in my React Native project.

TBH not really sure where it's picking up that your bundle.js needs es2015 or stage0?! I'm not a package maintainer, so this is venturing into the unknown for me.

However, based on what you say in #9 , it sounds like React Native support was never intended anyway.

**Comment by yury-dymov** [comment]
Yeah, this is correct. Hence, closing this. 

`es2015` and `stage-0` are not required this to work, unlike web environment.
