### ISSUE TITLE
React Native support?

### ISSUE THREAD

**Issue by njt1982** [yury-dymov/react-autocomplete-input#9]
Getting this error....

![image](https://user-images.githubusercontent.com/384976/29884938-df752760-8dac-11e7-88d7-5d4ecb316a29.png)

I'm importing it like this:

```
import {
  Input
} from 'native-base'

import TextField from 'react-autocomplete-input'
```

Tried this:
```
<TextField Component={Input} options={this.state.textOptions} />
```
and even:
```
<TextField options={this.state.textOptions} />
```

Any ideas? Other plugins seem to support the composite component approach: https://github.com/nathanhoad/react-timestamp#usage-with-react-native

**Comment by yury-dymov** [comment]
Well, I was not planning to support ReactNative explicitly. Maybe some changes are required to make this happen. 

PRs are welcome :)

**Comment by njt1982** [comment]
Looking through the src, it seems converting this for React Native may not be an insignificant task. I can see how the code is very much written for the web. Plenty of native web components like `li` and `span`. Also, the events are key and click based (although click translates to touch relatively well).

**Comment by yury-dymov** [comment]
@njt1982, well, I am not planning to use it in RN personally, so I am not going to tackle this. Probably it would be more efficient for you to find a RN alternative :) However, I am more than happy to review the PR and help with test/docs/whatever if you would like to drive this effort.

**Comment by yury-dymov** [comment]
I've learned a bit of react-native and believe that probably a better way would be developing the react-native-autocomplete package from scratch. Maybe ~20% of the logic can be reused.
