### ISSUE TITLE
Auto-complete on new word trigger doesn't work

### ISSUE THREAD

**Issue by barvhaim** [yury-dymov/react-autocomplete-input#95]
I am trying to auto-complete like `blah blah 1` -> the 1 won't open the auto completion, but when it is started with 1 like `1 ...` it will open the completion popup. how can I add completion in the middle of a sentence on new word? 

```
    <TextInput
            matchAny={true}
            trigger={''}
            options={["1.2.3.4"]} />
```

**Comment by yury-dymov** [comment]
From README:
<img width="459" alt="image" src="https://user-images.githubusercontent.com/1292558/217346223-a0c98ac0-f7d0-483b-a566-8ac74452d784.png">

**Comment by barvhaim** [comment]
@yury-dymov it's still not working, what I want to achieve is to be able to write some text words and then to make the autocompletion for a latter word, for example `one two three @ap` and the `@ap` would open the completion popup for `apple`
